import { NewsletterModel } from "@/shared/prisma.model.shared";
import newsletterSchema from "@/app/api/v1/newsletter/newsletter.schema";
import newsletterConstants from "@/app/api/v1/newsletter/newsletter.constants";
import sharedResponseTypes from "@/shared/shared.response.types";

import asyncHandler from "@/util/asyncHandler";
import validateUnsupportedContent from "@/util/validateUnsupportedContent";
import parseAndValidateFormData from "@/util/parseAndValidateFormData";
import sendEmail from "@/lib/email";
import newsletterSelectionCriteria from "@/app/api/v1/newsletter/newsletter.selection.criteria";


const { OK, UNPROCESSABLE_ENTITY } = sharedResponseTypes;

/**
 * Represents the criteria used to select newsletters.
 *
 * The `selectionCriteria` variable stores an object that defines the parameters
 * or conditions for filtering and retrieving newsletters based on specific needs.
 * This variable is typically generated by calling the `newsletterSelectionCriteria()`
 * function, which returns the configured criteria object.
 *
 * Use this variable to encapsulate the logic for newsletter selection,
 * ensuring a consistent and reusable structure across the application.
 */
const selectionCriteria = newsletterSelectionCriteria();

/**
 * Handles the subscription process for the newsletter.
 *
 * This function validates the content type of the request, parses and validates the submitted form data,
 * checks if the email is already subscribed, and processes new subscriptions.
 * It sends appropriate email responses to the user for both successful subscriptions and cases where the email is already subscribed.
 *
 * Workflow:
 * 1. Validates the content type against allowed content types.
 * 2. Parses and validates the user input form data.
 * 3. Checks if the provided email address is already subscribed.
 * 4. Sends a notification email if the email is already subscribed.
 * 5. Creates a new subscription record if the email is not yet subscribed.
 * 6. Sends a "Subscription Successful" email upon successful subscription.
 * 7. Returns appropriate responses for different scenarios and errors.
 *
 * @param {Object} request - The incoming HTTP request object containing subscription data and metadata.
 * @param {Object} context - Contextual information shared across the operation (e.g., authentication details).
 * @returns {Promise<Object>} A response object indicating the success or failure of the subscription process.
 */
const handleSubscribeToNewsletter = async (request, context) => {
    // Validate content type
    const contentValidationResult = validateUnsupportedContent(request, newsletterConstants.allowedContentTypes);
    if (!contentValidationResult.isValid) {
        return contentValidationResult.response;
    }

    // Parse and validate form data
    const userInput = await parseAndValidateFormData(request, context, 'create', newsletterSchema);

    // Check if the email is already subscribed
    const existingSubscription = await NewsletterModel.findUnique({
        where: {
            email: userInput?.email,
        },
        select: selectionCriteria,
    });

    if (existingSubscription) {
        // Send "Already Subscribed" email
        const alreadySubscribedSubject = `You're already subscribed!`;
        const alreadySubscribedHtml = `
            <h3>Dear ${userInput.email},</h3>
            <p>You are already subscribed to our newsletter. Thank you for staying connected!</p>
            <p>If you have any questions, feel free to contact us.</p>
        `;

        const sendEmailToSubscriberResponse = await sendEmail(userInput.email, alreadySubscribedSubject, alreadySubscribedHtml);
        if (!sendEmailToSubscriberResponse?.messageId) {
            return UNPROCESSABLE_ENTITY(
                `Failed to send "Already Subscribed" email to ${userInput.email}.`,
                request
            );
        }

        return OK('User is already subscribed to the newsletter.', {}, request);
    }

    // Create a new "newsletter" entry in the database
    const createdNewsletter = await NewsletterModel.create({
        data: {
            email: userInput?.email,
        },
        select: newsletterSelectionCriteria(),
    });

    if (!createdNewsletter) {
        return UNPROCESSABLE_ENTITY('Failed to save newsletter email data.', {}, request);
    }

    // Prepare "Subscription Successful" email details
    const subscriptionSuccessSubject = `Welcome to our Newsletter!`;
    const subscriptionSuccessHtml = `
        <h3>Dear ${userInput.email},</h3>
        <p>Thank you for subscribing to our newsletter!</p>
        <p>You will now receive regular updates and exciting news from us.</p>
        <p>If you have any questions, feel free to contact us.</p>
    `;

    // Send "Subscription Successful" email
    const sendEmailToSubscriberResponse = await sendEmail(userInput.email, subscriptionSuccessSubject, subscriptionSuccessHtml);
    if (!sendEmailToSubscriberResponse?.messageId) {
        return UNPROCESSABLE_ENTITY(
            `Failed to send "Subscription Successful" email to ${userInput.email}.`,
            request
        );
    }

    // Send a success response
    return OK(
        'Newsletter subscription successful.',
        {},
        request
    );
};

/**
 * POST is an asynchronous handler function designed to handle HTTP POST requests.
 * It is specifically used for processing subscriptions to a newsletter.
 * Utilizes the `asyncHandler` wrapper to manage asynchronous operations and streamline error handling.
 *
 * @type {Function}
 * @function
 * @async
 */
export const POST = asyncHandler(handleSubscribeToNewsletter);
