name: Continuous Integration

on:
    workflow_call: # Makes this workflow reusable by other workflows
        inputs:
            branch:
                required: false
                type: string
                default: '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Log checkout commit
              run: echo "Checked out $(git rev-parse --short HEAD)"

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '23'

            - name: Log Node.js version
              run: echo "Using Node.js $(node -v)"

            - name: Install dependencies
              run: |
                  echo "Installing dependencies..."
                  yarn install
                  echo "Dependencies installed."

            - name: Run ESLint checks
              run: |
                  echo "Running lint checks..."
                  yarn eslint:check || exit 1
                  echo "Lint checks completed."

            - name: Run Prettier checks
              run: |
                  echo "Running Prettier checks..."
                  yarn prettier:check || exit 1
                  echo "Prettier checks completed."
